theme = "awesome-identity"
baseURL = "https://arshxb.github.io/home"
title = "Arshdeep Singh - Software Developer / Data Scientist"
languageCode = "en-US"
# Content without language indicator will default to this language
defaultContentLanguage = "en"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
PygmentsCodeFences = true
# Enable to turn relative URLs into absolute
canonifyURLs = true
# Do not convert the url/path to lowercase
disablePathToLower = false
# Enable Emoji emoticons support for page content
enableEmoji = true
# Update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo = true
# Enable generation of `robots.txt` file
enableRobotsTXT = true

# Google Analytics tracking ID
#googleAnalytics = "UA-96267122-2"


## Profile Configurations

#if base url has subdirectory, add that to the potrait url also, in this case /home
[params.profile]
  portrait = "/home/images/1638336701613.jpg"
  firstname = "Arshdeep"
  lastname = "Singh"
  title = "Software Developer"
  bio = """ 🦉Night Owl🦉
  
Currently pursuing a Master's degree in Computer Science from UT Arlington, where I'm diving deep into the realms of big data and graphs databases. 
My current research is in the fields of data mining and data analysis in large graph datasets and multilayered networks, and even venturing into the world of parallel and distributed computing.
Prior to that I have over three years of real-world experience working on a range of projects across various domains.

When it comes to software development, I'm passionate about crafting effective and scalable solutions tailored to intricate business requirements. I aim to seamlessly integrate emerging technologies to not only boost application performance but also create remarkable user experiences.
"""

## Contacts Configurations
[params.contacts]
  email = "axs9120@gmail.com"
  github = "arshxb"
  linkedin = "arshxb"
  instagram = "arshxb"
  ##gitlab = "john.smith"
  ##twitter = "john.smith"
  ##facebook = "john.smith"
  ##stackoverflow = "7919458"
  ##keybase = "john.smith"
  ##medium = "john.smith"
  ##xing = "john.smith"

## Actions Configurations
[[params.actions]]
  name = "My Resume"
  url = "https://raw.githubusercontent.com/arshxb/resume/master/arsh_resume_latest.pdf"
#[[params.actions]]
#  name = "Ask Me Anything"
#  url = "https://github.com/posquit0/ama"
#[[params.actions]]
#  name = "Buy Me a Coffee"
#  url = "https://buymeacoff.ee/posquit0"


## Footer Configurations
[params.footer]
  copyright = "© 2023 Arshdeep Singh | [Privacy Policy](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true


## Privacy Configurations (GDPR)
[privacy]
  [privacy.googleAnalytics]
    disable = false
    # Make the users’ IP addresses are anonymized within Google Analytics
    anonymizeIP = false
    # Make the GA templates respect the “Do Not Track” HTTP header
    respectDoNotTrack = false
    # Disable the use of Cookies and use Session Storage to Store the GA Client ID
    useSessionStorage = false
    


